### PR TITLE
Update Go words

### PR DESCRIPTION
**Pull request by AlekSi**
Generated with https://github.com/AlekSi/go-words. Do not merge it yet, let's discuss it first.

1. What is the right way to generate words? How plugin handles camelCase?
2. May we split go.txt to several files? For example, go.txt will be generated by my tool, go_extra.txt can be updated by hands. We can also have other files for popular third-party packages.
3. Can you extend dictionary loading code to skip comments? That way we can have headers like `// generated with https://github.com/AlekSi/go-words`.
4. I still need to check performance with such a big dictionary.

### CODE REVIEW

**Comment by Jason-Rev** [comment]
Hey Alex,

Thank you for the contribution!  Wow!

I'll take a look and get back to you and exactly how word lists are ingested.

**Comment by Jason-Rev** [comment]
I am writing an update that will allow them to be used as they are.

**Comment by AlekSi** [comment]
Well, it's up to you. Just keep in mind that it's easy for me to modify generator program. For example, I can split names to words (`"TrimRight"` => `["Trim", "Right"]`, `"TrimRightFunc"` => `["Trim", "Right", "Func"]`). This can reduce a number of unique words significatly.

**Comment by AlekSi** [comment]
(Also FYI: Alex is a short form for Alexander, and I'm Alexey, that's a [different](https://en.wikipedia.org/wiki/Alexey) name 😄)

**Pull request merged**
