### PR TITLE
Enable for Haxe by default

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Jason3S** [comment]
Hello Gama11,

Thank you.  Is there a dictionary of words it should be associated with?  I don't know Haxe, it looks a bit like javascript or typescript.

This change will turn it on by default for people installing this plugin.  I just want to make sure they won't get a lot of errors for Haxe keywords.

Cheers,
Jason

**Comment by Gama11** [comment]
I haven't noticed any issues with keywords specifically, however, there are some common standard library functions that are labeled as errors. Not sure if you handle those specially too?

Examples include `concat()`, `ltrim()`, `rtrim()`, `typeof()`, `substr()` etc...

**Comment by Jason3S** [comment]
That is the type of stuff I was referring to.  Before I turn a language on by default, I try to make sure I have all the keywords and standard library methods in a dictionary file (it is just a simple text file).

You can easily turn on / off spell checking for a language:
image

Just click on the Haxe.  A window will open up and you can enable / disable the language.

**Comment by Gama11** [comment]
That just opens up a blank page for me:



There's an error in the dev console:

>[Embedded Page] Uncaught TypeError: Cannot read property 'scrollTop' of null

**Comment by Jason3S** [comment]
That must have broken with the 1.9 release.  I'll take a look now.

**Comment by Jason3S** [comment]
I have updated the extension to fix the issue with VS Code 1.9.

Please update the extension to 0.17.0 and try it again.

**Comment by Gama11** [comment]
Works fine now! 👍

**Comment by Jason3S** [comment]
If you get me a list of Haxe keywords and common library names, we can turn Haxe on by default.

Cheers,
Jason

**Comment by Gama11** [comment]
I can definitely work on that... I already have a pretty long list of "userWords" built-up.

It seems like a lot (or even all) of they keywords are already covered by the English dictionary. But I guess you need a complete keyword list if you want to switch (non-programming) languages?

**Comment by Jason3S** [comment]
Exactly!  The idea is to be able to change the base language from English to French or Spanish and have things still workout.

Although the reality is that most people will most likely have English and French turned on at the same time.

**Comment by Gama11** [comment]
I see. Yeah, it's pretty hard to imagine someone successfully disabling English.. Given that even if were to write all your code in say, French, most API calls you make to third-party libraries and whatnot would still be in English.

**Comment by Jason3S** [comment]
If you would like to make a pull request with keywords for Haxe to [cspell](https://github.com/Jason3S/cspell), then I can take this one once cspell has been updated.

In the mean time, I'm going to close this one.

**Pull request closed without merging**
