### PR TITLE
npm audit fix and npm update

### PR DESCRIPTION
**Pull request by zawataki**
Doesn't use a version containing a vulnerability.

### CODE REVIEW

**Comment by Jason3S** [comment]
Thank you.
I have a bigger fix coming in.

**Comment by deepkolos** [comment]
installServerIntoExtension copy node_modules's not enough to run the server when i install dependentes npm 6.9.0

i solve this runtime problem by manually copy server/node_modules to client/server/node_modules

**Comment by zawataki** [comment]
@Jason3S I got it. Is it better to close this issue?

**Comment by Jason3S** [comment]
> @Jason3S I got it. Is it better to close this issue?

Thank you. I'll close it.

**Comment by zawataki** [comment]
@Jason3S Thanks. I'm looking forward to seeing your big change.

**Pull request closed without merging**
